# Generated by Django 4.2.7 on 2023-11-29 02:21

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                ("questionname", models.CharField(max_length=300)),
                (
                    "id",
                    models.IntegerField(default=1, primary_key=True, serialize=False),
                ),
                ("a", models.CharField(max_length=150, null=True)),
                ("b", models.CharField(max_length=150, null=True)),
                ("c", models.CharField(max_length=150, null=True)),
                ("d", models.CharField(max_length=150, null=True)),
                ("answer", models.CharField(default="a", max_length=1, null=True)),
            ],
        ),
    ]
