# Generated by Django 4.1 on 2023-07-08 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sitting',
            fields=[
                ('name', models.CharField(default='', max_length=100)),
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('schedule', models.DateTimeField(null=True, verbose_name='schedule')),
                ('exam', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams', to='exams.exam')),
            ],
        ),
        migrations.CreateModel(
            name='CandidateRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sitting', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidaterequests', to='sittings.sitting')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_sittingrequests', to='accounts.userprofileinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sitting', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidates', to='sittings.sitting')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_sittings', to='accounts.userprofileinfo')),
            ],
        ),
    ]
