# Generated by Django 4.1 on 2023-07-08 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sittings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitting',
            name='length',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
